### ISSUE TITLE
PHP Warning: filemtime(): stat failed

### ISSUE THREAD

**Issue by derastronaut** [agoat/contao-imageondemand#3]
Hallo,

seit dem Contao-Update von 3.5.19 auf 3.5.20 füllen sich die error.logs sekündlich mit Fehlen dieser Art. Ursache scheint die Erweiterung "Image On Demand" zu sein, denn nach dessen Deaktivierung ist es still bei den Logs.

Gruß
Sebastian

```
[22-Dec-2016 00:00:34 Europe/Berlin] 
PHP Warning: filemtime(): stat failed for /www/htdocs/wurst/assets/images/g/tsv-tribuenentalk_2013-02-08-df3f87a9.jpg in /www/htdocs/wurst/system/modules/core/library/Contao/File.php on line 239
#0 [internal function]: __error(2, 'filemtime(): st...', '/www/htdocs/wur...', 239, Array)
#1 /www/htdocs/wurst/system/modules/core/library/Contao/File.php(239): filemtime('/www/htdocs/wur...')
#2 /www/htdocs/wurst/system/modules/core/library/Contao/File.php(253): Contao\File->__get('mtime')
#3 /www/htdocs/wurst/system/modules/core/library/Contao/Controller.php(1551): Contao\File->__get('imageSize')
#4 /www/htdocs/wurst/system/modules/news/modules/ModuleNews.php(199): Contao\Controller::addImageToTemplate(Object(Contao\FrontendTemplate), Array)
#5 /www/htdocs/wurst/system/modules/news/modules/ModuleNewsReader.php(108): Contao\ModuleNews->parseArticle(Object(Contao\NewsModel))
#6 /www/htdocs/wurst/system/modules/tags/modules/ModuleNewsReaderTags.php(26): Contao\ModuleNewsReader->compile()
#7 /www/htdocs/wurst/system/modules/core/modules/Module.php(287): Contao\ModuleNewsReaderTags->compile()
#8 /www/htdocs/wurst/system/modules/news/modules/ModuleNewsReader.php(82): Contao\Module->generate()
#9 /www/htdocs/wurst/system/modules/core/library/Contao/Controller.php(321): Contao\ModuleNewsReader->generate()
#10 /www/htdocs/wurst/system/modules/news/modules/ModuleNewsArchive.php(61): Contao\Controller::getFrontendModule('9', 'main')
#11 /www/htdocs/wurst/system/modules/core/elements/ContentModule.php(59): Contao\ModuleNewsArchive->generate()
#12 /www/htdocs/wurst/system/modules/core/library/Contao/Controller.php(484): Contao\ContentModule->generate()
#13 /www/htdocs/wurst/system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#14 /www/htdocs/wurst/system/modules/tags/modules/ModuleArticle.php(26): Contao\ModuleArticle->compile()
#15 /www/htdocs/wurst/system/modules/core/modules/Module.php(287): Aurealis\ModuleArticle->compile()
#16 /www/htdocs/wurst/system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#17 /www/htdocs/wurst/system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
#18 /www/htdocs/wurst/system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#19 /www/htdocs/wurst/system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#20 /www/htdocs/wurst/system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#21 /www/htdocs/wurst/index.php(20): Contao\FrontendIndex->run()
#22 {main}
```

**Comment by agoat** [comment]
In contao 3.5.20 some changes caused this failure. Fixed in 5f8c2fd754a402a9f6fb9b4a4fab39df803bcf35.

**Comment by reluem** [comment]
unfortunately, this issue still persists on Contao 3.5.24 (PHP 7).

```
[01-Feb-2017 11:33:17 Europe/Berlin] 
PHP Warning: filemtime(): stat failed for /is/htdocs/xxx/www/xxx/assets/images/g/IMG_8157-0ee8f097.jpg in /is/htdocs/xxx/www/xxx/system/modules/core/library/Contao/File.php on line 239
#0 [internal function]: __error_enhanced(2, 'filemtime(): stat failed for assets/images/g/IMG_8157-0ee8f097.jpg', 'system/modules/core/library/Contao/File.php', 239, Array)
#1 system/modules/core/library/Contao/File.php(239): filemtime('assets/images/g/IMG_8157-0ee8f097.jpg')
#2 system/modules/core/library/Contao/File.php(253): Contao\File->__get('mtime')
#3 system/modules/core/library/Contao/Controller.php(1551): Contao\File->__get('imageSize')
#4 system/modules/core/elements/ContentGallery.php(356): Contao\Controller::addImageToTemplate(stdClass, Array, 250, 'lightbox[lb230]')
#5 system/modules/core/elements/ContentElement.php(265): Contao\ContentGallery->compile()
#6 system/modules/core/elements/ContentGallery.php(76): Contao\ContentElement->generate()
#7 system/modules/core/library/Contao/Controller.php(484): Contao\ContentGallery->generate()
#8 system/modules/news/modules/ModuleNews.php(144): Contao\Controller::getContentElement(Contao\ContentModel)
#9 system/modules/core/library/Contao/Template.php(125): Contao\ModuleNews->Contao\{closure}()
#10 templates/news_latest_Nachrichten.html5(14): Contao\Template->__get('text')
#11 system/modules/core/library/Contao/BaseTemplate.php(88): include('templates/news_latest_Nachrichten.html5')
#12 system/modules/core/library/Contao/Template.php(277): Contao\BaseTemplate->parse()
#13 system/modules/core/classes/FrontendTemplate.php(46): Contao\Template->parse()
#14 system/modules/news/modules/ModuleNews.php(221): Contao\FrontendTemplate->parse()
#15 system/modules/news/modules/ModuleNews.php(250): Contao\ModuleNews->parseArticle(NewsCategories\NewsModel, false, ' last odd', 8)
#16 system/modules/news/modules/ModuleNewsArchive.php(198): Contao\ModuleNews->parseArticles(Contao\Model\Collection)
#17 system/modules/core/modules/Module.php(287): Contao\ModuleNewsArchive->compile()
#18 system/modules/news/modules/ModuleNewsArchive.php(70): Contao\Module->generate()
#19 composer/vendor/codefog/contao-news_categories/modules/ModuleNewsArchive.php(34): Contao\ModuleNewsArchive->generate()
#20 system/modules/core/elements/ContentModule.php(59): NewsCategories\ModuleNewsArchive->generate()
#21 system/modules/core/library/Contao/Controller.php(484): Contao\ContentModule->generate()
#22 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Contao\ContentModel, 'main')
#23 system/modules/core/modules/Module.php(287): Contao\ModuleArticle->compile()
#24 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#25 system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
#26 system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Contao\ArticleModel, false, false, 'main')
#27 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#28 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Contao\PageModel, true)
#29 index.php(20): Contao\FrontendIndex->run()
```
I manually installed the files from latest release here, because the packagist version is still one release behind.

Thanks!

**Comment by agoat** [comment]
I will check this.

**Comment by agoat** [comment]
Ok, I tested it with the newest contao 3.5.24 version but couldn't find any problem.

Have you cleared the internal cache? 
In your error log it looks like it still uses the core file class. The files class is overwritten from this extension to be able to handel virtual files, as the images just not exists on page generation.

**Comment by reluem** [comment]
okay, Internal cache was indeed the problem.
No more errors, but also no images unfortunately!

Is there any change in using template variables now? specifically, I am using the normale picture routine `<?php $this->insert('picture_default', $this->picture); ?>`, but this does not output the images anymore.
There are no corresponding files in the assets folder:
![nachrichten-bild 4014817921](https://cloud.githubusercontent.com/assets/17430489/22505719/433787b4-e87d-11e6-9770-5bd974f4512a.jpeg)

Error and system logs are empty..

**Comment by agoat** [comment]
No, there is no change.

If you installed it manually, did you also copy .htaccess and the images.php file to the assets folder??

**Comment by reluem** [comment]
yes, I copied the whole content of downloaded .zip to the root folder in composer->vendor->contao-legacy->imageondemand

the error still persists...
Could you maybe push the 2.2 version to packagist as well? maybe this helps!

**Comment by agoat** [comment]
If you installed it manually in the compser folder, you have to set symlinks to the assets/images folder. Otherwise the server will not find the .htaccess wich rewrites the call to /g/image.jpg to the image.php inside the assets/images folder.

Sorry, I don't have controll over the update of the ER2 to the C-C-A packagist server. You have to send a message to the CCA. In the ER2 the last version is shown correctly.

**Comment by reluem** [comment]
Actually, I overwrote the files already existing in the composer vendor folder from the latest available packagist install.
So all symlinks should already be in place.
In fact, the latest (v2.2) version of both .htaccess and image.php are in the assets folder.
Still, no images are shown.

The system is looking for files in assets/images/g/[xyz], but there is no folder /g in images.
Thus I think that the images are not even generated..


I contacted the c-c-a for an update.

**Comment by agoat** [comment]
Then I don't know why it's not working.
The images will not be generated in the /g folder. That's the trick. That's why I have to overwrite the files, images and pictures class. It's a virtual path wich will be rewritten by the .htaccess to the images.php for generation.
I never used composer in contao 3.5 because it was to buggy. And now I only work with contao 4.

**Comment by reluem** [comment]
hi, so in the meantime version 2.2 has been added to composer.
However, image generation is still only partially working.

I think the problem might be special chars in file names.
e.g. `IMG-21123-123.jpg ` is being generated, while `201231 blabla - Kopie(1).img` is not (fictious names).

Could this be the problem? thanks!

**Comment by agoat** [comment]
Yes. Some names (like with a `()`) will not work. 
You shouldn't use special character in file names for the web anyway.

**Comment by reluem** [comment]
hi, I can confirm that special characters (and even blank spaces) are the cause for the problem.

Without shell access it is quite a task to update all filenames accordingly, but in combination with [numero2/contao-proper-filenames](https://github.com/numero2/contao-proper-filenames) a download & reupload works quite OK.

However, just wanted to check if you could possibly add log entries for failed image generations (meaning these paths with special chars). This would certainly help all users of this add-on!

**Comment by agoat** [comment]
In Contao 4 it works also with names with special chars.

This extensions is depreciated in Contao 4 as it is replaced with the [agoat/deferredimages-bundle](https://github.com/agoat/contao-deferredimages-bundle/releases) extension.
